version: "3.7"

services:
  db:
    image: postgres:15.1
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: equinoccio
      POSTGRES_USER: equinoccio
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: equinocciotechnology@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
    depends_on:
      - db