
### -> Motivo por ID

GET http://localhost:3000/obras-madera-motivos-pases/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzdWFyaW8iOiJsbW9yZW5vIiwiYXBlbGxpZG8iOiJNT1JFTk8iLCJub21icmUiOiJMVUNBUyBPTUFSIiwicm9sZSI6IkFETUlOX1JPTEUiLCJpYXQiOjE2ODE0MjYzNzgsImV4cCI6MTY4MTQ2OTU3OH0.mali1ZUC9-dPevQgpeQ4e6zPuhxjRccUDyNb2JSxtW8
Content-Type: application/json

### -> Listar motivos

GET http://localhost:3000/obras-madera-motivos-pases
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzdWFyaW8iOiJsbW9yZW5vIiwiYXBlbGxpZG8iOiJNT1JFTk8iLCJub21icmUiOiJMVUNBUyBPTUFSIiwicm9sZSI6IkFETUlOX1JPTEUiLCJpYXQiOjE2ODE0MjYzNzgsImV4cCI6MTY4MTQ2OTU3OH0.mali1ZUC9-dPevQgpeQ4e6zPuhxjRccUDyNb2JSxtW8
Content-Type: application/json

### -> Nuevo motivo 

POST http://localhost:3000/obras-madera-motivos-pases
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzdWFyaW8iOiJsbW9yZW5vIiwiYXBlbGxpZG8iOiJNT1JFTk8iLCJub21icmUiOiJMVUNBUyBPTUFSIiwicm9sZSI6IkFETUlOX1JPTEUiLCJpYXQiOjE2ODE0MjYzNzgsImV4cCI6MTY4MTQ2OTU3OH0.mali1ZUC9-dPevQgpeQ4e6zPuhxjRccUDyNb2JSxtW8
Content-Type: application/json

{
    "descripcion": "Falta de materiales",
    "creatorUser": 2,
    "updatorUser": 2
}

### -> Actualizar motivo

PATCH http://localhost:3000/obras-madera-motivos-pases/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzdWFyaW8iOiJsbW9yZW5vIiwiYXBlbGxpZG8iOiJNT1JFTk8iLCJub21icmUiOiJMVUNBUyBPTUFSIiwicm9sZSI6IkFETUlOX1JPTEUiLCJpYXQiOjE2ODE0MjYzNzgsImV4cCI6MTY4MTQ2OTU3OH0.mali1ZUC9-dPevQgpeQ4e6zPuhxjRccUDyNb2JSxtW8
Content-Type: application/json

{
    "descripcion": "Falta de materiales",
    "updatorUser": 2
}